import random
from Generators.grenade_generator import generate_grenade
from Generators.relic_generator import generate_relic
from Generators.potion_generator import generate_potion
from Generators.gun_generator import generate_gun
from Generators.shield_generator import generate_shield
from Generators.save_generator import save_to_file
import random



import random

def generate_combat_scenario():
	# Dictionary of quest types
	quest_types = {
		1: "Quest : Rescue Mission	",
		2: "Quest : Bounty Hunt	",
		3: "Quest : Artifact Retrieval	",
		4: "Quest : Sabotage Operation	",
		5: "Quest : Escort Mission	",
		6: "Quest : Assassination Contract	",
		7: "Quest : Survival Challenge	",
		8: "Quest : Exploration Expedition	",
		9: "Quest : Data Recovery	",
		10: "Quest : Defend the Fortification	",
		11: "Quest : Reconnaissance Task	",
		12: "Quest : Stealth Infiltration	",
		13: "Quest : Interstellar Diplomacy	",
		14: "Quest : Hunting Grounds	",
		15: "Quest : Relic Investigation	",
		16: "Quest : Emergency Evacuation	",
		17: "Quest : Hazardous Material Cleanup	",
		18: "Quest : Extermination Campaign	",
		19: "Quest : Ancient Relic Translation	",
		20: "Quest : Technology Salvage	",
		21: "Quest : Undercover Operation	",
		22: "Quest : Raid on Enemy Base	",
		23: "Quest : Rogue AI Elimination	",
		24: "Quest : Prisoner Extraction	",
		25: "Quest : Ritual Disruption	",
		26: "Quest : Cursed Artifact Retrieval	",
		27: "Quest : Invasion Defense	",
		28: "Quest : Tactical Retreat	",
		29: "Quest : Criminal Syndicate Takedown	",
		30: "Quest : Wildlife Conservation	",
		31: "Quest : Underground Resistance Support	",
		32: "Quest : Artifact Smuggling Interception	",
		33: "Quest : Virus Containment	",
		34: "Quest : Underworld Negotiation	",
		35: "Quest : Rogue Scientist Apprehension	",
		36: "Quest : Supply Run	",
		37: "Quest : Lost Colony Investigation	",
		38: "Quest : Space Piracy Suppression	",
		39: "Quest : Resource Extraction	",
		40: "Quest : Botanical Research	",
		41: "Quest : Mercenary Contract	",
		42: "Quest : Arms Dealer Bust	",
		43: "Quest : Alien Artifact Analysis	",
		44: "Quest : Celestial Phenomenon Observation	",
		45: "Quest : Wasteland Patrol	",
		46: "Quest : Infiltrate Corporate Headquarters	",
		47: "Quest : Rogue Planet Exploration	",
		48: "Quest : Rescue Stranded Travelers	",
		49: "Quest : Prevent Hostile Takeover	",
		50: "Quest : Dungeon Delve	"
	}

	# Dictionary of locations
	locations = {
		1: "Location : Abandoned Mine	",
		2: "Location : Desert Oasis	",
		3: "Location : Haunted Forest	",
		4: "Location : Urban Ruins	",
		5: "Location : Volcanic Wasteland	",
		6: "Location : Frozen Tundra	",
		7: "Location : Space Station	",
		8: "Location : Underground Bunker	",
		9: "Location : Jungle Temple	",
		10: "Location : Alien Mothership	",
		11: "Location : Mystic Swamp	",
		12: "Location : Floating City	",
		13: "Location : Crystal Caves	",
		14: "Location : Hidden Valley	",
		15: "Location : Subterranean City	",
		16: "Location : Dimensional Rift	",
		17: "Location : Lost Civilization Ruins	",
		18: "Location : Sunken Ship	",
		19: "Location : Radioactive Wasteland	",
		20: "Location : Sky Fortress	",
		21: "Location : Ancient Observatory	",
		22: "Location : Asteroid Belt	",
		23: "Location : Underwater City	",
		24: "Location : Forbidden Temple	",
		25: "Location : Toxic Jungle	",
		26: "Location : Iceberg Citadel	",
		27: "Location : Underworld Nexus	",
		28: "Location : Stormy Seas	",
		29: "Location : Ghost Town	",
		30: "Location : Crashed Spaceship	",
		31: "Location : Dark Matter Nebula	",
		32: "Location : Underground Labyrinth	",
		33: "Location : Floating Islands	",
		34: "Location : Urban Sprawl	",
		35: "Location : Celestial Battlefield	",
		36: "Location : Skyrim Peaks	",
		37: "Location : Abyssal Depths	",
		38: "Location : Interstellar Trade Hub	",
		39: "Location : Forgotten Fortress	",
		40: "Location : Techno-City	",
		41: "Location : Lost World	",
		42: "Location : Hidden Monastery	",
		43: "Location : Infested Hive	",
		44: "Location : Alien Research Facility	",
		45: "Location : Crystal Mountain	",
		46: "Location : Haunted Mansion	",
		47: "Location : Thundering Plains	",
		48: "Location : Solar Flare Canyon	",
		49: "Location : Toxic Waste Dump	",
		50: "Location : Savage Highlands	"
	}

	# Dictionary of enemies
	enemies = {
		1: "Enemy Type : Cultist	",
		2: "Enemy Type : Bandit	",
		3: "Enemy Type : Martyr	",
		4: "Enemy Type : Badass Cultist	",
		5: "Enemy Type : Badass Bandit	",
		6: "Enemy Type : Badass Martyr	",
		7: "Enemy Type : Baby Dragon	",
		8: "Enemy Type : Blue Dragon	",
		9: "Enemy Type : Red Dragon	",
		10: "Enemy Type : Green Dragon	",
		11: "Enemy Type : Yellow Dragon	",
		12: "Enemy Type : Badass Baby Dragon	",
		13: "Enemy Type : Badass Blue Dragon	",
		14: "Enemy Type : Badass Red Dragon	",
		15: "Enemy Type : Badass Green Dragon	",
		16: "Enemy Type : Badass Yellow Dragon	",
		17: "Enemy Type : Dwarf	",
		18: "Enemy Type : Dwarf Miner	",
		19: "Enemy Type : Dwarfzerker	",
		20: "Enemy Type : Badass Dwarf	",
		21: "Enemy Type : Badass Dwarf Miner	",
		22: "Enemy Type : Badass Dwarfzerker	",
		23: "Enemy Type : Goblin	",
		24: "Enemy Type : Potion Master	",
		25: "Enemy Type : Goblin Cannoneer	",
		26: "Enemy Type : Bomb Boi	",
		27: "Enemy Type : Goblin Engineer	",
		28: "Enemy Type : Badass Goblin	",
		29: "Enemy Type : Badass Alchemist	",
		30: "Enemy Type : Badass Cannoneer	",
		31: "Enemy Type : Badass Bomber	",
		32: "Enemy Type : Badass Engineer	",
		33: "Enemy Type : Rock Golem	",
		34: "Enemy Type : Iron Golem	",
		35: "Enemy Type : Badass Rock Golem	",
		36: "Enemy Type : Badass Iron Golem	",
		37: "Enemy Type : Knight	",
		38: "Enemy Type : Archer	",
		39: "Enemy Type : Paladin	",
		40: "Enemy Type : Squire	",
		41: "Enemy Type : Death Knight	",
		42: "Enemy Type : Badass Knight	",
		43: "Enemy Type : Badass Archer	",
		44: "Enemy Type : Badass Paladin	",
		45: "Enemy Type : Badass Squire	",
		46: "Enemy Type : Badass Death Knight	",
		47: "Enemy Type : Mimic	",
		48: "Enemy Type : Badass Mimic	",
		49: "Enemy Type : Orc Basher	",
		50: "Enemy Type : Orc Warrior	",
		51: "Enemy Type : Orc Bushwhacker	",
		52: "Enemy Type : Orc Warlord	",
		53: "Enemy Type : Badass Orc Basher	",
		54: "Enemy Type : Badass Orc Warrior	",
		55: "Enemy Type : Badass Bushwhacker	",
		56: "Enemy Type : Badass Orc Warlord	",
		57: "Enemy Type : Pixie	",
		58: "Enemy Type : Badass Pixie	",
		60: "Enemy Type : Unknown	",
		61: "Enemy Type : Unknown	",
		62: "Enemy Type : Unknown	",
		63: "Enemy Type : Unknown	",
		64: "Enemy Type : Unknown	",
		65: "Enemy Type : Unknown	",
		66: "Enemy Type : Unknown	",
		67: "Enemy Type : Unknown	",
		68: "Enemy Type : Unknown	",
		69: "Enemy Type : Unknown	",
		70: "Enemy Type : Unknown	",
		}


	random_quest_type_key = random.choice(list(quest_types.keys()))
	random_quest_type = quest_types[random_quest_type_key]
	random_location_key = random.choice(list(locations.keys()))
	random_location = locations[random_location_key]
	random_enemies_key = random.choice(list(enemies.keys()))
	random_enemies = enemies[random_enemies_key]

	return f"{random_quest_type} : {random_location} : {random_enemies}"